# Generated by Django 2.1 on 2018-11-16 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Observacion', models.CharField(max_length=200)),
                ('Imagen', models.ImageField(upload_to='')),
                ('EstadoDenuncia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('IdBarrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Barrio')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('Puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Loggin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaIngreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('EstadoId', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('FechaNacimiento', models.DateTimeField()),
                ('EstadoId', models.BooleanField()),
                ('IdDireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Direccion')),
                ('IdPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='loggin',
            name='IdMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Menu'),
        ),
        migrations.AddField(
            model_name='loggin',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Usuario'),
        ),
        migrations.AddField(
            model_name='juego',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Usuario'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='IdTipoVivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.TipoVivienda'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Usuario'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='IdLocalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Localidad'),
        ),
    ]
